/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Components: typeof import('./src/components/index.ts')['default']
    Form: typeof import('./src/components/Form.tsx')['default']
    Menu: typeof import('./src/components/Menu.tsx')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NFlew: typeof import('naive-ui')['NFlew']
    NFlex: typeof import('naive-ui')['NFlex']
    NFlow: typeof import('naive-ui')['NFlow']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    PopoverButton: typeof import('./src/components/PopoverButton.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.tsx')['default']
    TooltipButton: typeof import('./src/components/TooltipButton.tsx')['default']
  }
}
