/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasisFrom: typeof import('./components/BasisFrom.tsx')['default']
    CardCodeEditor: typeof import('./components/CardCodeEditor.tsx')['default']
    Components: typeof import('./components/index.ts')['default']
    'Components.d': typeof import('./components/components.d.ts')['default']
    CustomTable: typeof import('./components/CustomTable.tsx')['default']
    Form: typeof import('./components/Form.tsx')['default']
    FormEditorButton: typeof import('./components/FormEditorButton.tsx')['default']
    JsonConfigDrawer: typeof import('./components/JsonConfigDrawer.tsx')['default']
    Menu: typeof import('./components/Menu.tsx')['default']
    ProTable: typeof import('./components/ProTable.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFrom: typeof import('./components/SearchFrom.tsx')['default']
    SearchInput: typeof import('./components/SearchInput.tsx')['default']
    TooltipButton: typeof import('./components/TooltipButton.tsx')['default']
    UseDrawer: typeof import('./components/useDrawer.tsx')['default']
  }
}
